<?php

namespace Drupal\iso3166\Service;

use Drupal\Core\StringTranslation\StringTranslationTrait;
use Drupal\Core\DependencyInjection\ContainerInjectionInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\Core\StringTranslation\TranslationInterface;

/**
 * Class DataProvider.
 *
 * @package Drupal\iso3611
 * @SuppressWarnings(ExcessiveClassLength)
 */
class DataProvider implements ContainerInjectionInterface {

  use StringTranslationTrait;

  /**
   * {@inheritdoc}
   */
  public function __construct(TranslationInterface $stringTranslation) {
    $this->stringTranslation = $stringTranslation;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('string_translation')
    );
  }

  /**
   * {@inheritdoc}
   *
   * @SuppressWarnings(ExcessiveMethodLength)
   */
  public function getList() {
    return [
      [
        'alpha2' => 'AF',
        'label' => $this->t('Africa'),
        'countries' => [
          [
            'name' => $this->t('Algeria'),
            'alpha2' => 'DZ',
            'alpha3' => 'DZA',
            'numeric' => '012',
          ],
          [
            'name' => $this->t('Angola'),
            'alpha2' => 'AO',
            'alpha3' => 'AGO',
            'numeric' => '024',
          ],
          [
            'name' => $this->t('Benin'),
            'alpha2' => 'BJ',
            'alpha3' => 'BEN',
            'numeric' => '204',
          ],
          [
            'name' => $this->t('Botswana'),
            'alpha2' => 'BW',
            'alpha3' => 'BWA',
            'numeric' => '072',
          ],
          [
            'name' => $this->t('Burkina Faso'),
            'alpha2' => 'BF',
            'alpha3' => 'BFA',
            'numeric' => '854',
          ],
          [
            'name' => $this->t('Burundi'),
            'alpha2' => 'BI',
            'alpha3' => 'BDI',
            'numeric' => '108',
          ],
          [
            'name' => $this->t('Cabo Verde'),
            'alpha2' => 'CV',
            'alpha3' => 'CPV',
            'numeric' => '132',
          ],
          [
            'name' => $this->t('Cameroon'),
            'alpha2' => 'CM',
            'alpha3' => 'CMR',
            'numeric' => '120',
          ],
          [
            'name' => $this->t('Central African Republic'),
            'alpha2' => 'CF',
            'alpha3' => 'CAF',
            'numeric' => '140',
          ],
          [
            'name' => $this->t('Chad'),
            'alpha2' => 'TD',
            'alpha3' => 'TCD',
            'numeric' => '148',
          ],
          [
            'name' => $this->t('Comoros'),
            'alpha2' => 'KM',
            'alpha3' => 'COM',
            'numeric' => '174',
          ],
          [
            'name' => $this->t('Congo'),
            'alpha2' => 'CG',
            'alpha3' => 'COG',
            'numeric' => '178',
          ],
          [
            'name' => $this->t('Congo (Democratic Republic of the)'),
            'alpha2' => 'CD',
            'alpha3' => 'COD',
            'numeric' => '180',
          ],
          [
            'name' => $this->t("Côte d'Ivoire"),
            'alpha2' => 'CI',
            'alpha3' => 'CIV',
            'numeric' => '384',
          ],
          [
            'name' => $this->t('Djibouti'),
            'alpha2' => 'DJ',
            'alpha3' => 'DJI',
            'numeric' => '262',
          ],
          [
            'name' => $this->t('Egypt'),
            'alpha2' => 'EG',
            'alpha3' => 'EGY',
            'numeric' => '818',
          ],
          [
            'name' => $this->t('Equatorial Guinea'),
            'alpha2' => 'GQ',
            'alpha3' => 'GNQ',
            'numeric' => '226',
          ],
          [
            'name' => $this->t('Eritrea'),
            'alpha2' => 'ER',
            'alpha3' => 'ERI',
            'numeric' => '232',
          ],
          [
            'name' => $this->t('Ethiopia'),
            'alpha2' => 'ET',
            'alpha3' => 'ETH',
            'numeric' => '231',
          ],
          [
            'name' => $this->t('Eswatini, the Kingdom of'),
            'alpha2' => 'SZ',
            'alpha3' => 'SWZ',
            'numeric' => '748',
          ],
          [
            'name' => $this->t('Gabon'),
            'alpha2' => 'GA',
            'alpha3' => 'GAB',
            'numeric' => '266',
          ],
          [
            'name' => $this->t('Gambia'),
            'alpha2' => 'GM',
            'alpha3' => 'GMB',
            'numeric' => '270',
          ],
          [
            'name' => $this->t('Ghana'),
            'alpha2' => 'GH',
            'alpha3' => 'GHA',
            'numeric' => '288',
          ],
          [
            'name' => $this->t('Guinea'),
            'alpha2' => 'GN',
            'alpha3' => 'GIN',
            'numeric' => '324',
          ],
          [
            'name' => $this->t('Guinea-Bissau'),
            'alpha2' => 'GW',
            'alpha3' => 'GNB',
            'numeric' => '624',
          ],
          [
            'name' => $this->t('Kenya'),
            'alpha2' => 'KE',
            'alpha3' => 'KEN',
            'numeric' => '404',
          ],
          [
            'name' => $this->t('Lesotho'),
            'alpha2' => 'LS',
            'alpha3' => 'LSO',
            'numeric' => '426',
          ],
          [
            'name' => $this->t('Liberia'),
            'alpha2' => 'LR',
            'alpha3' => 'LBR',
            'numeric' => '430',
          ],
          [
            'name' => $this->t('Libya'),
            'alpha2' => 'LY',
            'alpha3' => 'LBY',
            'numeric' => '434',
          ],
          [
            'name' => $this->t('Madagascar'),
            'alpha2' => 'MG',
            'alpha3' => 'MDG',
            'numeric' => '450',
          ],
          [
            'name' => $this->t('Malawi'),
            'alpha2' => 'MW',
            'alpha3' => 'MWI',
            'numeric' => '454',
          ],
          [
            'name' => $this->t('Mali'),
            'alpha2' => 'ML',
            'alpha3' => 'MLI',
            'numeric' => '466',
          ],
          [
            'name' => $this->t('Mauritania'),
            'alpha2' => 'MR',
            'alpha3' => 'MRT',
            'numeric' => '478',
          ],
          [
            'name' => $this->t('Mauritius'),
            'alpha2' => 'MU',
            'alpha3' => 'MUS',
            'numeric' => '480',
          ],
          [
            'name' => $this->t('Mayotte'),
            'alpha2' => 'YT',
            'alpha3' => 'MYT',
            'numeric' => '175',
          ],
          [
            'name' => $this->t('Morocco'),
            'alpha2' => 'MA',
            'alpha3' => 'MAR',
            'numeric' => '504',
          ],
          [
            'name' => $this->t('Mozambique'),
            'alpha2' => 'MZ',
            'alpha3' => 'MOZ',
            'numeric' => '508',
          ],
          [
            'name' => $this->t('Namibia'),
            'alpha2' => 'NA',
            'alpha3' => 'NAM',
            'numeric' => '516',
          ],
          [
            'name' => $this->t('Niger'),
            'alpha2' => 'NE',
            'alpha3' => 'NER',
            'numeric' => '562',
          ],
          [
            'name' => $this->t('Nigeria'),
            'alpha2' => 'NG',
            'alpha3' => 'NGA',
            'numeric' => '566',
          ],
          [
            'name' => $this->t('Réunion'),
            'alpha2' => 'RE',
            'alpha3' => 'REU',
            'numeric' => '638',
          ],
          [
            'name' => $this->t('Rwanda'),
            'alpha2' => 'RW',
            'alpha3' => 'RWA',
            'numeric' => '646',
          ],
          [
            'name' => $this->t('Saint Helena, Ascension and Tristan da Cunha'),
            'alpha2' => 'SH',
            'alpha3' => 'SHN',
            'numeric' => '654',
          ],
          [
            'name' => $this->t('Sao Tome and Principe'),
            'alpha2' => 'ST',
            'alpha3' => 'STP',
            'numeric' => '678',
          ],
          [
            'name' => $this->t('Senegal'),
            'alpha2' => 'SN',
            'alpha3' => 'SEN',
            'numeric' => '686',
          ],
          [
            'name' => $this->t('Seychelles'),
            'alpha2' => 'SC',
            'alpha3' => 'SYC',
            'numeric' => '690',
          ],
          [
            'name' => $this->t('Sierra Leone'),
            'alpha2' => 'SL',
            'alpha3' => 'SLE',
            'numeric' => '694',
          ],
          [
            'name' => $this->t('Somalia'),
            'alpha2' => 'SO',
            'alpha3' => 'SOM',
            'numeric' => '706',
          ],
          [
            'name' => $this->t('South Africa'),
            'alpha2' => 'ZA',
            'alpha3' => 'ZAF',
            'numeric' => '710',
          ],
          [
            'name' => $this->t('South Sudan'),
            'alpha2' => 'SS',
            'alpha3' => 'SSD',
            'numeric' => '728',
          ],
          [
            'name' => $this->t('Sudan'),
            'alpha2' => 'SD',
            'alpha3' => 'SDN',
            'numeric' => '729',
          ],
          [
            'name' => $this->t('Tanzania, United Republic of'),
            'alpha2' => 'TZ',
            'alpha3' => 'TZA',
            'numeric' => '834',
          ],
          [
            'name' => $this->t('Togo'),
            'alpha2' => 'TG',
            'alpha3' => 'TGO',
            'numeric' => '768',
          ],
          [
            'name' => $this->t('Tunisia'),
            'alpha2' => 'TN',
            'alpha3' => 'TUN',
            'numeric' => '788',
          ],
          [
            'name' => $this->t('Uganda'),
            'alpha2' => 'UG',
            'alpha3' => 'UGA',
            'numeric' => '800',
          ],
          [
            'name' => $this->t('Western Sahara'),
            'alpha2' => 'EH',
            'alpha3' => 'ESH',
            'numeric' => '732',
          ],
          [
            'name' => $this->t('Zambia'),
            'alpha2' => 'ZM',
            'alpha3' => 'ZMB',
            'numeric' => '894',
          ],
          [
            'name' => $this->t('Zimbabwe'),
            'alpha2' => 'ZW',
            'alpha3' => 'ZWE',
            'numeric' => '716',
          ],
        ],
      ],
      [
        'alpha2' => 'AN',
        'label' => $this->t('Antarctica'),
        'countries' => [
          [
            'name' => $this->t('Bouvet Island'),
            'alpha2' => 'BV',
            'alpha3' => 'BVT',
            'numeric' => '074',
          ],
          [
            'name' => $this->t('South Georgia and the South Sandwich Islands'),
            'alpha2' => 'GS',
            'alpha3' => 'SGS',
            'numeric' => '239',
          ],
          [
            'name' => $this->t('Heard Island and McDonald Islands'),
            'alpha2' => 'HM',
            'alpha3' => 'HMD',
            'numeric' => '334',
          ],
          [
            'name' => $this->t('French Southern Territories'),
            'alpha2' => 'TF',
            'alpha3' => 'ATF',
            'numeric' => '260',
          ],
          [
            'name' => $this->t('Antarctica'),
            'alpha2' => 'AQ',
            'alpha3' => 'ATA',
            'numeric' => '010',
          ],
        ],
      ],
      [
        'alpha2' => 'AS',
        'label' => $this->t('Asia'),
        'countries' => [
          [
            'name' => $this->t('Afghanistan'),
            'alpha2' => 'AF',
            'alpha3' => 'AFG',
            'numeric' => '004',
          ],
          [
            'name' => $this->t('Bangladesh'),
            'alpha2' => 'BD',
            'alpha3' => 'BGD',
            'numeric' => '050',
          ],
          [
            'name' => $this->t('Brunei Darussalam'),
            'alpha2' => 'BN',
            'alpha3' => 'BRN',
            'numeric' => '096',
          ],
          [
            'name' => $this->t('Bahrain'),
            'alpha2' => 'BH',
            'alpha3' => 'BHR',
            'numeric' => '048',
          ],
          [
            'name' => $this->t('Bhutan'),
            'alpha2' => 'BT',
            'alpha3' => 'BTN',
            'numeric' => '064',
          ],
          [
            'name' => $this->t('Turkmenistan'),
            'alpha2' => 'TM',
            'alpha3' => 'TKM',
            'numeric' => '795',
          ],
          [
            'name' => $this->t('Tajikistan'),
            'alpha2' => 'TJ',
            'alpha3' => 'TJK',
            'numeric' => '762',
          ],
          [
            'name' => $this->t('Japan'),
            'alpha2' => 'JP',
            'alpha3' => 'JPN',
            'numeric' => '392',
          ],
          [
            'name' => $this->t('Georgia'),
            'alpha2' => 'GE',
            'alpha3' => 'GEO',
            'numeric' => '268',
          ],
          [
            'name' => $this->t('Oman'),
            'alpha2' => 'OM',
            'alpha3' => 'OMN',
            'numeric' => '512',
          ],
          [
            'name' => $this->t('Jordan'),
            'alpha2' => 'JO',
            'alpha3' => 'JOR',
            'numeric' => '400',
          ],
          [
            'name' => $this->t('Hong Kong'),
            'alpha2' => 'HK',
            'alpha3' => 'HKG',
            'numeric' => '344',
          ],
          [
            'name' => $this->t('Palestine, State of'),
            'alpha2' => 'PS',
            'alpha3' => 'PSE',
            'numeric' => '275',
          ],
          [
            'name' => $this->t('Iraq'),
            'alpha2' => 'IQ',
            'alpha3' => 'IRQ',
            'numeric' => '368',
          ],
          [
            'name' => $this->t('Pakistan'),
            'alpha2' => 'PK',
            'alpha3' => 'PAK',
            'numeric' => '586',
          ],
          [
            'name' => $this->t('Philippines'),
            'alpha2' => 'PH',
            'alpha3' => 'PHL',
            'numeric' => '608',
          ],
          [
            'name' => $this->t('Viet Nam'),
            'alpha2' => 'VN',
            'alpha3' => 'VNM',
            'numeric' => '704',
          ],
          [
            'name' => $this->t('Saudi Arabia'),
            'alpha2' => 'SA',
            'alpha3' => 'SAU',
            'numeric' => '682',
          ],
          [
            'name' => $this->t('Uzbekistan'),
            'alpha2' => 'UZ',
            'alpha3' => 'UZB',
            'numeric' => '860',
          ],
          [
            'name' => $this->t('Myanmar'),
            'alpha2' => 'MM',
            'alpha3' => 'MMR',
            'numeric' => '104',
          ],
          [
            'name' => $this->t('Macao'),
            'alpha2' => 'MO',
            'alpha3' => 'MAC',
            'numeric' => '446',
          ],
          [
            'name' => $this->t('Mongolia'),
            'alpha2' => 'MN',
            'alpha3' => 'MNG',
            'numeric' => '496',
          ],
          [
            'name' => $this->t('Maldives'),
            'alpha2' => 'MV',
            'alpha3' => 'MDV',
            'numeric' => '462',
          ],
          [
            'name' => $this->t('Malaysia'),
            'alpha2' => 'MY',
            'alpha3' => 'MYS',
            'numeric' => '458',
          ],
          [
            'name' => $this->t('Israel'),
            'alpha2' => 'IL',
            'alpha3' => 'ISR',
            'numeric' => '376',
          ],
          [
            'name' => $this->t('British Indian Ocean Territory'),
            'alpha2' => 'IO',
            'alpha3' => 'IOT',
            'numeric' => '086',
          ],
          [
            'name' => $this->t('Nepal'),
            'alpha2' => 'NP',
            'alpha3' => 'NPL',
            'numeric' => '524',
          ],
          [
            'name' => $this->t('China'),
            'alpha2' => 'CN',
            'alpha3' => 'CHN',
            'numeric' => '156',
          ],
          [
            'name' => $this->t('Cocos (Keeling) Islands'),
            'alpha2' => 'CC',
            'alpha3' => 'CCK',
            'numeric' => '166',
          ],
          [
            'name' => $this->t('Christmas Island'),
            'alpha2' => 'CX',
            'alpha3' => 'CXR',
            'numeric' => '162',
          ],
          [
            'name' => $this->t('Syrian Arab Republic'),
            'alpha2' => 'SY',
            'alpha3' => 'SYR',
            'numeric' => '760',
          ],
          [
            'name' => $this->t('Kyrgyzstan'),
            'alpha2' => 'KG',
            'alpha3' => 'KGZ',
            'numeric' => '417',
          ],
          [
            'name' => $this->t('Cambodia'),
            'alpha2' => 'KH',
            'alpha3' => 'KHM',
            'numeric' => '116',
          ],
          [
            'name' => $this->t('Korea (Republic of))'),
            'alpha2' => 'KR',
            'alpha3' => 'KOR',
            'numeric' => '410',
          ],
          [
            'name' => $this->t("Korea (Democratic People's Republic of)"),
            'alpha2' => 'KP',
            'alpha3' => 'PRK',
            'numeric' => '408',
          ],
          [
            'name' => $this->t('Kuwait'),
            'alpha2' => 'KW',
            'alpha3' => 'KWT',
            'numeric' => '414',
          ],
          [
            'name' => $this->t('Kazakhstan'),
            'alpha2' => 'KZ',
            'alpha3' => 'KAZ',
            'numeric' => '398',
          ],
          [
            'name' => $this->t('Singapore'),
            'alpha2' => 'SG',
            'alpha3' => 'SGP',
            'numeric' => '702',
          ],
          [
            'name' => $this->t('Yemen'),
            'alpha2' => 'YE',
            'alpha3' => 'YEM',
            'numeric' => '887',
          ],
          [
            'name' => $this->t('Lebanon'),
            'alpha2' => 'LB',
            'alpha3' => 'LBN',
            'numeric' => '422',
          ],
          [
            'name' => $this->t("Lao People's Democratic Republic"),
            'alpha2' => 'LA',
            'alpha3' => 'LAO',
            'numeric' => '418',
          ],
          [
            'name' => $this->t('Taiwan (Province of China)'),
            'alpha2' => 'TW',
            'alpha3' => 'TWN',
            'numeric' => '158',
          ],
          [
            'name' => $this->t('Turkey'),
            'alpha2' => 'TR',
            'alpha3' => 'TUR',
            'numeric' => '792',
          ],
          [
            'name' => $this->t('Sri Lanka'),
            'alpha2' => 'LK',
            'alpha3' => 'LKA',
            'numeric' => '144',
          ],
          [
            'name' => $this->t('Thailand'),
            'alpha2' => 'TH',
            'alpha3' => 'THA',
            'numeric' => '764',
          ],
          [
            'name' => $this->t('United Arab Emirates'),
            'alpha2' => 'AE',
            'alpha3' => 'ARE',
            'numeric' => '784',
          ],
          [
            'name' => $this->t('Iran (Islamic Republic of)'),
            'alpha2' => 'IR',
            'alpha3' => 'IRN',
            'numeric' => '364',
          ],
          [
            'name' => $this->t('Armenia'),
            'alpha2' => 'AM',
            'alpha3' => 'ARM',
            'numeric' => '051',
          ],
          [
            'name' => $this->t('India'),
            'alpha2' => 'IN',
            'alpha3' => 'IND',
            'numeric' => '356',
          ],
          [
            'name' => $this->t('Azerbaijan'),
            'alpha2' => 'AZ',
            'alpha3' => 'AZE',
            'numeric' => '031',
          ],
          [
            'name' => $this->t('Indonesia'),
            'alpha2' => 'ID',
            'alpha3' => 'IDN',
            'numeric' => '360',
          ],
          [
            'name' => $this->t('Qatar'),
            'alpha2' => 'QA',
            'alpha3' => 'QAT',
            'numeric' => '634',
          ],
        ],
      ],
      [
        'alpha2' => 'EU',
        'label' => $this->t('Europe'),
        'countries' => [
          [
            'name' => $this->t('Belgium'),
            'alpha2' => 'BE',
            'alpha3' => 'BEL',
            'numeric' => '056',
          ],
          [
            'name' => $this->t('Bulgaria'),
            'alpha2' => 'BG',
            'alpha3' => 'BGR',
            'numeric' => '100',
          ],
          [
            'name' => $this->t('Bosnia and Herzegovina'),
            'alpha2' => 'BA',
            'alpha3' => 'BIH',
            'numeric' => '070',
          ],
          [
            'name' => $this->t('Jersey'),
            'alpha2' => 'JE',
            'alpha3' => 'JEY',
            'numeric' => '832',
          ],
          [
            'name' => $this->t('Belarus'),
            'alpha2' => 'BY',
            'alpha3' => 'BLR',
            'numeric' => '112',
          ],
          [
            'name' => $this->t('Russian Federation'),
            'alpha2' => 'RU',
            'alpha3' => 'RUS',
            'numeric' => '643',
          ],
          [
            'name' => $this->t('Serbia'),
            'alpha2' => 'RS',
            'alpha3' => 'SRB',
            'numeric' => '688',
          ],
          [
            'name' => $this->t('Romania'),
            'alpha2' => 'RO',
            'alpha3' => 'ROU',
            'numeric' => '642',
          ],
          [
            'name' => $this->t('Greece'),
            'alpha2' => 'GR',
            'alpha3' => 'GRC',
            'numeric' => '300',
          ],
          [
            'name' => $this->t('Guernsey'),
            'alpha2' => 'GG',
            'alpha3' => 'GGY',
            'numeric' => '831',
          ],
          [
            'name' => $this->t('United Kingdom of Great Britain and Northern Ireland'),
            'alpha2' => 'GB',
            'alpha3' => 'GBR',
            'numeric' => '826',
          ],
          [
            'name' => $this->t('Gibraltar'),
            'alpha2' => 'GI',
            'alpha3' => 'GIB',
            'numeric' => '292',
          ],
          [
            'name' => $this->t('Croatia'),
            'alpha2' => 'HR',
            'alpha3' => 'HRV',
            'numeric' => '191',
          ],
          [
            'name' => $this->t('Hungary'),
            'alpha2' => 'HU',
            'alpha3' => 'HUN',
            'numeric' => '348',
          ],
          [
            'name' => $this->t('Portugal'),
            'alpha2' => 'PT',
            'alpha3' => 'PRT',
            'numeric' => '620',
          ],
          [
            'name' => $this->t('Svalbard and Jan Mayen'),
            'alpha2' => 'SJ',
            'alpha3' => 'SJM',
            'numeric' => '744',
          ],
          [
            'name' => $this->t('Poland'),
            'alpha2' => 'PL',
            'alpha3' => 'POL',
            'numeric' => '616',
          ],
          [
            'name' => $this->t('Estonia'),
            'alpha2' => 'EE',
            'alpha3' => 'EST',
            'numeric' => '233',
          ],
          [
            'name' => $this->t('Italy'),
            'alpha2' => 'IT',
            'alpha3' => 'ITA',
            'numeric' => '380',
          ],
          [
            'name' => $this->t('Spain'),
            'alpha2' => 'ES',
            'alpha3' => 'ESP',
            'numeric' => '724',
          ],
          [
            'name' => $this->t('Montenegro'),
            'alpha2' => 'ME',
            'alpha3' => 'MNE',
            'numeric' => '499',
          ],
          [
            'name' => $this->t('Moldova (Republic of)'),
            'alpha2' => 'MD',
            'alpha3' => 'MDA',
            'numeric' => '498',
          ],
          [
            'name' => $this->t('Monaco'),
            'alpha2' => 'MC',
            'alpha3' => 'MCO',
            'numeric' => '492',
          ],
          [
            'name' => $this->t('Macedonia (the former Yugoslav Republic of)'),
            'alpha2' => 'MK',
            'alpha3' => 'MKD',
            'numeric' => '807',
          ],
          [
            'name' => $this->t('Malta'),
            'alpha2' => 'MT',
            'alpha3' => 'MLT',
            'numeric' => '470',
          ],
          [
            'name' => $this->t('Isle of Man'),
            'alpha2' => 'IM',
            'alpha3' => 'IMN',
            'numeric' => '833',
          ],
          [
            'name' => $this->t('France'),
            'alpha2' => 'FR',
            'alpha3' => 'FRA',
            'numeric' => '250',
          ],
          [
            'name' => $this->t('Finland'),
            'alpha2' => 'FI',
            'alpha3' => 'FIN',
            'numeric' => '246',
          ],
          [
            'name' => $this->t('Faroe Islands'),
            'alpha2' => 'FO',
            'alpha3' => 'FRO',
            'numeric' => '234',
          ],
          [
            'name' => $this->t('Netherlands'),
            'alpha2' => 'NL',
            'alpha3' => 'NLD',
            'numeric' => '528',
          ],
          [
            'name' => $this->t('Norway'),
            'alpha2' => 'NO',
            'alpha3' => 'NOR',
            'numeric' => '578',
          ],
          [
            'name' => $this->t('Switzerland'),
            'alpha2' => 'CH',
            'alpha3' => 'CHE',
            'numeric' => '756',
          ],
          [
            'name' => $this->t('Czechia'),
            'alpha2' => 'CZ',
            'alpha3' => 'CZE',
            'numeric' => '203',
          ],
          [
            'name' => $this->t('Cyprus'),
            'alpha2' => 'CY',
            'alpha3' => 'CYP',
            'numeric' => '196',
          ],
          [
            'name' => $this->t('Slovakia'),
            'alpha2' => 'SK',
            'alpha3' => 'SVK',
            'numeric' => '703',
          ],
          [
            'name' => $this->t('Slovenia'),
            'alpha2' => 'SI',
            'alpha3' => 'SVN',
            'numeric' => '705',
          ],
          [
            'name' => $this->t('San Marino'),
            'alpha2' => 'SM',
            'alpha3' => 'SMR',
            'numeric' => '674',
          ],
          [
            'name' => $this->t('Sweden'),
            'alpha2' => 'SE',
            'alpha3' => 'SWE',
            'numeric' => '752',
          ],
          [
            'name' => $this->t('Denmark'),
            'alpha2' => 'DK',
            'alpha3' => 'DNK',
            'numeric' => '208',
          ],
          [
            'name' => $this->t('Germany'),
            'alpha2' => 'DE',
            'alpha3' => 'DEU',
            'numeric' => '276',
          ],
          [
            'name' => $this->t('Liechtenstein'),
            'alpha2' => 'LI',
            'alpha3' => 'LIE',
            'numeric' => '438',
          ],
          [
            'name' => $this->t('Latvia'),
            'alpha2' => 'LV',
            'alpha3' => 'LVA',
            'numeric' => '428',
          ],
          [
            'name' => $this->t('Lithuania'),
            'alpha2' => 'LT',
            'alpha3' => 'LTU',
            'numeric' => '440',
          ],
          [
            'name' => $this->t('Luxembourg'),
            'alpha2' => 'LU',
            'alpha3' => 'LUX',
            'numeric' => '442',
          ],
          [
            'name' => $this->t('Holy See'),
            'alpha2' => 'VA',
            'alpha3' => 'VAT',
            'numeric' => '336',
          ],
          [
            'name' => $this->t('Andorra'),
            'alpha2' => 'AD',
            'alpha3' => 'AND',
            'numeric' => '020',
          ],
          [
            'name' => $this->t('Iceland'),
            'alpha2' => 'IS',
            'alpha3' => 'ISL',
            'numeric' => '352',
          ],
          [
            'name' => $this->t('Albania'),
            'alpha2' => 'AL',
            'alpha3' => 'ALB',
            'numeric' => '008',
          ],
          [
            'name' => $this->t('Austria'),
            'alpha2' => 'AT',
            'alpha3' => 'AUT',
            'numeric' => '040',
          ],
          [
            'name' => $this->t('Åland Islands'),
            'alpha2' => 'AX',
            'alpha3' => 'ALA',
            'numeric' => '248',
          ],
          [
            'name' => $this->t('Ireland'),
            'alpha2' => 'IE',
            'alpha3' => 'IRL',
            'numeric' => '372',
          ],
          [
            'name' => $this->t('Ukraine'),
            'alpha2' => 'UA',
            'alpha3' => 'UKR',
            'numeric' => '804',
          ],
        ],
      ],
      [
        'alpha2' => 'NA',
        'label' => $this->t('North america'),
        'countries' => [
          [
            'name' => $this->t('Barbados'),
            'alpha2' => 'BB',
            'alpha3' => 'BRB',
            'numeric' => '052',
          ],
          [
            'name' => $this->t('Saint Barthélemy'),
            'alpha2' => 'BL',
            'alpha3' => 'BLM',
            'numeric' => '652',
          ],
          [
            'name' => $this->t('Bermuda'),
            'alpha2' => 'BM',
            'alpha3' => 'BMU',
            'numeric' => '060',
          ],
          [
            'name' => $this->t('Jamaica'),
            'alpha2' => 'JM',
            'alpha3' => 'JAM',
            'numeric' => '388',
          ],
          [
            'name' => $this->t('Bonaire, Sint Eustatius and Saba'),
            'alpha2' => 'BQ',
            'alpha3' => 'BES',
            'numeric' => '535',
          ],
          [
            'name' => $this->t('Belize'),
            'alpha2' => 'BZ',
            'alpha3' => 'BLZ',
            'numeric' => '084',
          ],
          [
            'name' => $this->t('Guatemala'),
            'alpha2' => 'GT',
            'alpha3' => 'GTM',
            'numeric' => '320',
          ],
          [
            'name' => $this->t('Guadeloupe'),
            'alpha2' => 'GP',
            'alpha3' => 'GLP',
            'numeric' => '312',
          ],
          [
            'name' => $this->t('Grenada'),
            'alpha2' => 'GD',
            'alpha3' => 'GRD',
            'numeric' => '308',
          ],
          [
            'name' => $this->t('El Salvador'),
            'alpha2' => 'SV',
            'alpha3' => 'SLV',
            'numeric' => '222',
          ],
          [
            'name' => $this->t('Greenland'),
            'alpha2' => 'GL',
            'alpha3' => 'GRL',
            'numeric' => '304',
          ],
          [
            'name' => $this->t('Haiti'),
            'alpha2' => 'HT',
            'alpha3' => 'HTI',
            'numeric' => '332',
          ],
          [
            'name' => $this->t('Honduras'),
            'alpha2' => 'HN',
            'alpha3' => 'HND',
            'numeric' => '340',
          ],
          [
            'name' => $this->t('Puerto Rico'),
            'alpha2' => 'PR',
            'alpha3' => 'PRI',
            'numeric' => '630',
          ],
          [
            'name' => $this->t('Panama'),
            'alpha2' => 'PA',
            'alpha3' => 'PAN',
            'numeric' => '591',
          ],
          [
            'name' => $this->t('Saint Pierre and Miquelon'),
            'alpha2' => 'PM',
            'alpha3' => 'SPM',
            'numeric' => '666',
          ],
          [
            'name' => $this->t('Saint Martin (French part)'),
            'alpha2' => 'MF',
            'alpha3' => 'MAF',
            'numeric' => '663',
          ],
          [
            'name' => $this->t('Martinique'),
            'alpha2' => 'MQ',
            'alpha3' => 'MTQ',
            'numeric' => '474',
          ],
          [
            'name' => $this->t('Montserrat'),
            'alpha2' => 'MS',
            'alpha3' => 'MSR',
            'numeric' => '500',
          ],
          [
            'name' => $this->t('Mexico'),
            'alpha2' => 'MX',
            'alpha3' => 'MEX',
            'numeric' => '484',
          ],
          [
            'name' => $this->t('Nicaragua'),
            'alpha2' => 'NI',
            'alpha3' => 'NIC',
            'numeric' => '558',
          ],
          [
            'name' => $this->t('Canada'),
            'alpha2' => 'CA',
            'alpha3' => 'CAN',
            'numeric' => '124',
          ],
          [
            'name' => $this->t('Costa Rica'),
            'alpha2' => 'CR',
            'alpha3' => 'CRI',
            'numeric' => '188',
          ],
          [
            'name' => $this->t('Curaçao'),
            'alpha2' => 'CW',
            'alpha3' => 'CUW',
            'numeric' => '531',
          ],
          [
            'name' => $this->t('Cuba'),
            'alpha2' => 'CU',
            'alpha3' => 'CUB',
            'numeric' => '192',
          ],
          [
            'name' => $this->t('Sint Maarten (Dutch part)'),
            'alpha2' => 'SX',
            'alpha3' => 'SXM',
            'numeric' => '534',
          ],
          [
            'name' => $this->t('Saint Kitts and Nevis'),
            'alpha2' => 'KN',
            'alpha3' => 'KNA',
            'numeric' => '659',
          ],
          [
            'name' => $this->t('Cayman Islands'),
            'alpha2' => 'KY',
            'alpha3' => 'CYM',
            'numeric' => '136',
          ],
          [
            'name' => $this->t('Dominican Republic'),
            'alpha2' => 'DO',
            'alpha3' => 'DOM',
            'numeric' => '214',
          ],
          [
            'name' => $this->t('Dominica'),
            'alpha2' => 'DM',
            'alpha3' => 'DMA',
            'numeric' => '212',
          ],
          [
            'name' => $this->t('Virgin Islands (British)'),
            'alpha2' => 'VG',
            'alpha3' => 'VGB',
            'numeric' => '092',
          ],
          [
            'name' => $this->t('United States of America'),
            'alpha2' => 'US',
            'alpha3' => 'USA',
            'numeric' => '840',
          ],
          [
            'name' => $this->t('Saint Lucia'),
            'alpha2' => 'LC',
            'alpha3' => 'LCA',
            'numeric' => '662',
          ],
          [
            'name' => $this->t('Trinidad and Tobago'),
            'alpha2' => 'TT',
            'alpha3' => 'TTO',
            'numeric' => '780',
          ],
          [
            'name' => $this->t('Turks and Caicos Islands'),
            'alpha2' => 'TC',
            'alpha3' => 'TCA',
            'numeric' => '796',
          ],
          [
            'name' => $this->t('Saint Vincent and the Grenadines'),
            'alpha2' => 'VC',
            'alpha3' => 'VCT',
            'numeric' => '670',
          ],
          [
            'name' => $this->t('Antigua and Barbuda'),
            'alpha2' => 'AG',
            'alpha3' => 'ATG',
            'numeric' => '028',
          ],
          [
            'name' => $this->t('Anguilla'),
            'alpha2' => 'AI',
            'alpha3' => 'AIA',
            'numeric' => '660',
          ],
          [
            'name' => $this->t('Virgin Islands (U.S.)'),
            'alpha2' => 'VI',
            'alpha3' => 'VIR',
            'numeric' => '850',
          ],
          [
            'name' => $this->t('Aruba'),
            'alpha2' => 'AW',
            'alpha3' => 'ABW',
            'numeric' => '533',
          ],
          [
            'name' => $this->t('Bahamas'),
            'alpha2' => 'BS',
            'alpha3' => 'BHS',
            'numeric' => '044',
          ],
        ],
      ],
      [
        'alpha2' => 'OC',
        'label' => $this->t('Oceania'),
        'countries' => [
          [
            'name' => $this->t('Wallis and Futuna'),
            'alpha2' => 'WF',
            'alpha3' => 'WLF',
            'numeric' => '876',
          ],
          [
            'name' => $this->t('Samoa'),
            'alpha2' => 'WS',
            'alpha3' => 'WSM',
            'numeric' => '882',
          ],
          [
            'name' => $this->t('Timor-Leste'),
            'alpha2' => 'TL',
            'alpha3' => 'TLS',
            'numeric' => '626',
          ],
          [
            'name' => $this->t('Tokelau'),
            'alpha2' => 'TK',
            'alpha3' => 'TKL',
            'numeric' => '772',
          ],
          [
            'name' => $this->t('Guam'),
            'alpha2' => 'GU',
            'alpha3' => 'GUM',
            'numeric' => '316',
          ],
          [
            'name' => $this->t('Palau'),
            'alpha2' => 'PW',
            'alpha3' => 'PLW',
            'numeric' => '585',
          ],
          [
            'name' => $this->t('French Polynesia'),
            'alpha2' => 'PF',
            'alpha3' => 'PYF',
            'numeric' => '258',
          ],
          [
            'name' => $this->t('Papua New Guinea'),
            'alpha2' => 'PG',
            'alpha3' => 'PNG',
            'numeric' => '598',
          ],
          [
            'name' => $this->t('Pitcairn'),
            'alpha2' => 'PN',
            'alpha3' => 'PCN',
            'numeric' => '612',
          ],
          [
            'name' => $this->t('Solomon Islands'),
            'alpha2' => 'SB',
            'alpha3' => 'SLB',
            'numeric' => '090',
          ],
          [
            'name' => $this->t('Marshall Islands'),
            'alpha2' => 'MH',
            'alpha3' => 'MHL',
            'numeric' => '584',
          ],
          [
            'name' => $this->t('Northern Mariana Islands'),
            'alpha2' => 'MP',
            'alpha3' => 'MNP',
            'numeric' => '580',
          ],
          [
            'name' => $this->t('Fiji'),
            'alpha2' => 'FJ',
            'alpha3' => 'FJI',
            'numeric' => '242',
          ],
          [
            'name' => $this->t('Micronesia (Federated States of)'),
            'alpha2' => 'FM',
            'alpha3' => 'FSM',
            'numeric' => '583',
          ],
          [
            'name' => $this->t('Vanuatu'),
            'alpha2' => 'VU',
            'alpha3' => 'VUT',
            'numeric' => '548',
          ],
          [
            'name' => $this->t('New Caledonia'),
            'alpha2' => 'NC',
            'alpha3' => 'NCL',
            'numeric' => '540',
          ],
          [
            'name' => $this->t('Norfolk Island'),
            'alpha2' => 'NF',
            'alpha3' => 'NFK',
            'numeric' => '574',
          ],
          [
            'name' => $this->t('New Zealand'),
            'alpha2' => 'NZ',
            'alpha3' => 'NZL',
            'numeric' => '554',
          ],
          [
            'name' => $this->t('Nauru'),
            'alpha2' => 'NR',
            'alpha3' => 'NRU',
            'numeric' => '520',
          ],
          [
            'name' => $this->t('Niue'),
            'alpha2' => 'NU',
            'alpha3' => 'NIU',
            'numeric' => '570',
          ],
          [
            'name' => $this->t('Cook Islands'),
            'alpha2' => 'CK',
            'alpha3' => 'COK',
            'numeric' => '184',
          ],
          [
            'name' => $this->t('Kiribati'),
            'alpha2' => 'KI',
            'alpha3' => 'KIR',
            'numeric' => '296',
          ],
          [
            'name' => $this->t('United States Minor Outlying Islands'),
            'alpha2' => 'UM',
            'alpha3' => 'UMI',
            'numeric' => '581',
          ],
          [
            'name' => $this->t('Tuvalu'),
            'alpha2' => 'TV',
            'alpha3' => 'TUV',
            'numeric' => '798',
          ],
          [
            'name' => $this->t('Tonga'),
            'alpha2' => 'TO',
            'alpha3' => 'TON',
            'numeric' => '776',
          ],
          [
            'name' => $this->t('American Samoa'),
            'alpha2' => 'AS',
            'alpha3' => 'ASM',
            'numeric' => '016',
          ],
          [
            'name' => $this->t('Australia'),
            'alpha2' => 'AU',
            'alpha3' => 'AUS',
            'numeric' => '036',
          ],
        ],
      ],
      [
        'alpha2' => 'SA',
        'label' => $this->t('South america'),
        'countries' => [
          [
            'name' => $this->t('Bolivia (Plurinational State of)'),
            'alpha2' => 'BO',
            'alpha3' => 'BOL',
            'numeric' => '068',
          ],
          [
            'name' => $this->t('Brazil'),
            'alpha2' => 'BR',
            'alpha3' => 'BRA',
            'numeric' => '076',
          ],
          [
            'name' => $this->t('Guyana'),
            'alpha2' => 'GY',
            'alpha3' => 'GUY',
            'numeric' => '328',
          ],
          [
            'name' => $this->t('French Guiana'),
            'alpha2' => 'GF',
            'alpha3' => 'GUF',
            'numeric' => '254',
          ],
          [
            'name' => $this->t('Venezuela (Bolivarian Republic of)'),
            'alpha2' => 'VE',
            'alpha3' => 'VEN',
            'numeric' => '862',
          ],
          [
            'name' => $this->t('Paraguay'),
            'alpha2' => 'PY',
            'alpha3' => 'PRY',
            'numeric' => '600',
          ],
          [
            'name' => $this->t('Peru'),
            'alpha2' => 'PE',
            'alpha3' => 'PER',
            'numeric' => '604',
          ],
          [
            'name' => $this->t('Ecuador'),
            'alpha2' => 'EC',
            'alpha3' => 'ECU',
            'numeric' => '218',
          ],
          [
            'name' => $this->t('Falkland Islands (Malvinas)'),
            'alpha2' => 'FK',
            'alpha3' => 'FLK',
            'numeric' => '238',
          ],
          [
            'name' => $this->t('Colombia'),
            'alpha2' => 'CO',
            'alpha3' => 'COL',
            'numeric' => '170',
          ],
          [
            'name' => $this->t('Chile'),
            'alpha2' => 'CL',
            'alpha3' => 'CHL',
            'numeric' => '152',
          ],
          [
            'name' => $this->t('Suriname'),
            'alpha2' => 'SR',
            'alpha3' => 'SUR',
            'numeric' => '740',
          ],
          [
            'name' => $this->t('Uruguay'),
            'alpha2' => 'UY',
            'alpha3' => 'URY',
            'numeric' => '858',
          ],
          [
            'name' => $this->t('Argentina'),
            'alpha2' => 'AR',
            'alpha3' => 'ARG',
            'numeric' => '032',
          ],
        ],
      ],
    ];
  }

}
